apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomize-config.yaml

resources:
  - sts.yaml
  - svc.yaml
  - pvc.yaml
  - ingress.yaml
  - middleware.yaml

generators:
  - ksops.yaml
