apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: csi-driver-nfs
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    version: 4.13.0
    releaseName: nfs
    namespace: nfs
    valuesFile: ./values.yaml
