apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: minecraft-be
  annotations:
    external-dns.alpha.kubernetes.io/target: "oci-lb.kentaro1043.com"
    external-dns.alpha.kubernetes.io/hostname: "sakura-mc.kentaro1043.com"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  entryPoints:
    - minecraft-be
  routes:
    - services:
        - name: minecraft-be
          port: 19132
