apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy.yaml
  - ./svc.yaml
  - ./ingress.yaml

helmCharts:
  - name: valkey
    repo: https://valkey.io/valkey-helm
    version: 0.8.1
    releaseName: misskey-valkey
    namespace: misskey
    valuesFile: valkey-values.yaml

generators:
  - ksops.yaml
