apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vaultwarden
    repo: https://guerzon.github.io/vaultwarden
    version: 0.34.6
    releaseName: vaultwarden
    namespace: vaultwarden
    valuesFile: ./values.yaml

generators:
  - ./ksops.yaml
