apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-metrics
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "traefik.kentaro1043.com"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.kentaro1043.com`) && PathPrefix(`/metrics`)
      kind: Rule
      services:
        - kind: TraefikService
          name: prometheus@internal
