apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sts.yaml
  - svc.yaml
  - cm.yaml
#  - ingress-route-udp.yaml

configMapGenerator:
  - name: minecraft-be-allowlist
    files:
      - config/allowlist.json
