apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sts.yaml
  - svc.yaml
  - ingress.yaml

configMapGenerator:
  - name: handscale-config
    files:
      - config.yaml=config/config.yaml
