global:
  domain: cd.kentaro1043.com

controller:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"

server:
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "100m"
  certificate:
    enabled: false
    issuer:
      name: http-01-issuer
      kind: ClusterIssuer
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      cert-manager.io/cluster-issuer: "http-01-issuer"
      external-dns.alpha.kubernetes.io/hostname: "cd.kentaro1043.com"
    tls: true

applicationSet:
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "100m"

redis-ha:
  enabled: false

### ksops configuration
### https://github.com/viaduct-ai/kustomize-sops#argo-cd-helm-chart-with-custom-tooling
# Enable Kustomize Alpha Plugins via Argo CD ConfigMap, required for ksops
configs:
  params:
    server.insecure: true
  cm:
    # ksops
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec --enable-helm"

    # helm-secrets
    helm.valuesFileSchemes: >-
      secrets+gpg-import, secrets+gpg-import-kubernetes,
      secrets+age-import, secrets+age-import-kubernetes,
      secrets,secrets+literal,
      https

    # GitHub webhook secret
    webhook.github.secret: $github-webhook-secret:secret

repoServer:
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "150m"
  env:
    # ksops & helm-secrets
    - name: XDG_CONFIG_HOME
      value: /.config
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/keys.txt

    # helm-secrets
    - name: HELM_PLUGINS
      value: /helm-secrets-bin/helm-plugins
    - name: HELM_SECRETS_CURL_PATH
      value: /helm-secrets-bin/curl
    - name: HELM_SECRETS_SOPS_PATH
      value: /helm-secrets-bin/sops
    - name: HELM_SECRETS_VALS_PATH
      value: /helm-secrets-bin/vals
    - name: HELM_SECRETS_KUBECTL_PATH
      value: /helm-secrets-bin/kubectl
    - name: HELM_SECRETS_HELM_PATH
      value: /usr/local/bin/helm
    - name: HELM_SECRETS_BACKEND
      value: sops
    # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
    - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
      value: "false"
    - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
      value: "true"
    - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
      value: "false"
    - name: HELM_SECRETS_WRAPPER_ENABLED
      value: "true"
    - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
      value: "true"

  # Use init containers to configure custom tooling
  # https://argoproj.github.io/argo-cd/operator-manual/custom_tools/
  volumes:
    # sops key for ksops & helm-secrets
    - name: sops-age
      secret:
        secretName: sops-age

    # ksops & helm-secrets
    - name: ksops-bin
      emptyDir: {}

    # helm-secrets
    - name: helm-secrets-bin
      emptyDir: {}

  initContainers:
    # ksops installation
    - name: install-ksops
      image: viaductoss/ksops:v4.3.3@sha256:6b5ec4b6144307f78bcddffd8f09020482836eee34cf77bf4ce8614b0452a73c
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing KSOPS...";
          mv ksops /ksops-bin/;
          mv kustomize /ksops-bin/;
          echo "Done.";
      volumeMounts:
        - mountPath: /ksops-bin
          name: ksops-bin

    # helm-secrets installation
    - name: install-helm-secrets
      image: alpine:latest@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412
      imagePullPolicy: IfNotPresent
      command: [sh, -ec]
      env:
        - name: HELM_SECRETS_VERSION
          value: "4.7.0"
        - name: KUBECTL_VERSION
          value: "1.33.1"
        - name: VALS_VERSION
          value: "0.42.4"
        - name: SOPS_VERSION
          value: "3.11.0"
        - name: STATIC_CURL_VERSION
          value: "8.17.0"
      args:
        - |
          echo "Starting installation of helm-secrets..."
          mkdir -p /helm-secrets-bin/helm-plugins

          echo "Installing static curl version ${STATIC_CURL_VERSION}..."
          GO_ARCH=$(uname -m | sed -e 's/x86_64/amd64/')
          wget -qO /tmp/curl.tar.xz https://github.com/stunnel/static-curl/releases/download/${STATIC_CURL_VERSION}/curl-linux-${GO_ARCH}-glibc-${STATIC_CURL_VERSION}.tar.xz
          tar -xJf /tmp/curl.tar.xz -C /helm-secrets-bin/ curl
          echo "Done."

          GO_ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')

          echo "Installing kubectl version ${KUBECTL_VERSION}..."
          wget -qO /helm-secrets-bin/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${GO_ARCH}/kubectl
          echo "Done."

          echo "Installing sops version ${SOPS_VERSION}..."
          wget -qO /helm-secrets-bin/sops https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.${GO_ARCH}
          echo "Done."

          echo "Installing vals version ${VALS_VERSION}..."
          wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_${GO_ARCH}.tar.gz | tar zxv -C /helm-secrets-bin vals
          echo "Done."

          echo "Installing helm-secrets version ${HELM_SECRETS_VERSION}..."
          wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /helm-secrets-bin/helm-plugins -xzf-
          echo "Done."

          chmod +x /helm-secrets-bin/*
          cp /helm-secrets-bin/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /helm-secrets-bin/helm

          echo "Installation of helm-secrets completed."
      volumeMounts:
        - mountPath: /helm-secrets-bin
          name: helm-secrets-bin

  volumeMounts:
    # ksops
    - mountPath: /usr/local/bin/ksops
      name: ksops-bin
      subPath: ksops
    # kustomize
    - mountPath: /usr/local/bin/kustomize
      name: ksops-bin
      subPath: kustomize

    # helm-secrets
    - mountPath: /helm-secrets-bin
      name: helm-secrets-bin
    - mountPath: /usr/local/sbin/helm
      subPath: helm
      name: helm-secrets-bin

    # sops key for ksops & helm-secrets
    - mountPath: /.config/sops/age
      name: sops-age

dex:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

notifications:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

  secret:
    create: false

  notifiers:
    service.webhook.discord: |
      url: $discord-webhook-url
      headers:
        - name: Content-Type
          value: "application/json"

  subscriptions:
    - recipients:
        - discord
      selector: skip-default-notification!=true
      triggers:
        - on-created
        - on-deleted
        - on-deployed
        - on-health-degraded
        - on-sync-failed
        - on-sync-running
        - on-sync-status-unknown

  templates:
    template.app-created: |
      webhook:
        discord:
          method: POST
          body: |
            {
              "content":"## :tada: [{{.app.metadata.name}}]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}) Created"
            }
    template.app-deleted: |
      webhook:
        discord:
          method: POST
          body: |
            {
              "content":"## :boom: [{{.app.metadata.name}}]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}) Deleted"
            }
    template.app-deployed: |
      webhook:
        discord:
          method: POST
          body: |
            {
              "content":"## :rocket: [{{.app.metadata.name}}]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}) for [`{{ substr 0 7 .app.status.sync.revision }}`](<https://github.com/Kentaro1043/manifest/commit/{{ .app.status.sync.revision }}>) Deployed"
            }
    template.app-health-degraded: |
      webhook:
        discord:
          method: POST
          body: |
            {
              "content":"## :fire: [{{.app.metadata.name}}]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}) Degraded"
            }
    template.app-sync-failed: |
      webhook:
        discord:
          method: POST
          body: |
            {
              "content":"## :exclamation: [{{.app.metadata.name}}]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}) Sync Failed"
            }
    template.app-sync-running: |
      webhook:
        discord:
          method: POST
          body: |
            {
              "content":"## :arrows_counterclockwise: [{{.app.metadata.name}}]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}) Syncing"
            }
    template.app-sync-status-unknown: |
      webhook:
        discord:
          method: POST
          body: |
            {
              "content":"## :question: [{{.app.metadata.name}}]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}) Sync Status Unknown"
            }

  # ref: https://github.com/argoproj/argo-cd/blob/master/notifications_catalog/install.yaml
  triggers:
    trigger.on-created: |
      - description: Application is created.
        oncePer: app.metadata.name
        send:
        - app-created
        when: "true"
    trigger.on-deleted: |
      - description: Application is deleted.
        oncePer: app.metadata.name
        send:
        - app-deleted
        when: app.metadata.deletionTimestamp != nil
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.operationState?.syncResult?.revision
        send:
        - app-deployed
        when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
          and app.status.health.status == 'Healthy' and (!time.Parse(app.status.health.lastTransitionTime).Add(1
          * time.Minute).Before(time.Parse(app.status.operationState.finishedAt)) or time.Parse(app.status.health.lastTransitionTime).Before(time.Parse(app.status.operationState.startedAt)))
    trigger.on-health-degraded: |
      - description: Application has degraded
        oncePer: app.status.operationState?.syncResult?.revision
        send:
        - app-health-degraded
        when: app.status.health.status == 'Degraded'
    trigger.on-sync-failed: |
      - description: Application syncing has failed
        oncePer: app.status.operationState?.syncResult?.revision
        send:
        - app-sync-failed
        when: app.status.operationState != nil and app.status.operationState.phase in ['Error',
          'Failed']
    trigger.on-sync-running: |
      - description: Application is being synced
        oncePer: app.status.operationState?.syncResult?.revision
        send:
        - app-sync-running
        when: app.status.operationState != nil and app.status.operationState.phase in ['Running']
    trigger.on-sync-status-unknown: |
      - description: Application status is 'Unknown'
        oncePer: app.status.operationState?.syncResult?.revision
        send:
        - app-sync-status-unknown
        when: app.status.sync.status == 'Unknown'
    trigger.on-sync-succeeded: |
      - description: Application syncing has succeeded
        oncePer: app.status.operationState?.syncResult?.revision
        send:
        - app-sync-succeeded
        when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
