apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomize-config.yaml

helmCharts:
  - name: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    version: 0.46.3
    releaseName: argo-workflows
    namespace: argo
    includeCRDs: true
    valuesFile: ./values.yaml

resources:
  - ingress.yaml
  - middleware.yaml

  - workflows/discord-notification.yaml
  - workflows/cgps.yaml

generators:
  - ksops.yaml
