server:
  authModes:
    - server
  resources:
    requests:
      memory: "32Mi"
      cpu: "10m"
    limits:
      memory: "48Mi"
      cpu: "20m"

workflow:
  serviceAccount:
    create: true
    name: "argo-workflow"
  rbac:
    create: true

controller:
  workflowDefaults:
    spec:
      onExit: discord-notification
      templates:
        - name: discord-notification
          steps:
            - - name: notify
                templateRef:
                  clusterScope: true
                  name: discord-notification
                  template: send-discord-notification
  resources:
    requests:
      memory: "36Mi"
      cpu: "10m"
    limits:
      memory: "72Mi"
      cpu: "20m"

  workflowNamespaces: []
