apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/containers[]/env[]/valueFrom/secretKeyRef/name
