apiVersion: kustomize.config.k8s.io/v1beta1
kind: Configuration

nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: Middleware
        path: spec/basicAuth/secret
      - kind: ClusterWorkflowTemplate
        path: spec/templates[]/container/env[]/valueFrom/secretKeyRef/name
      - kind: CronWorkflow
        path: spec/workflowSpec/templates[]/container/envFrom[]/secretRef/name
