apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns
    version: 1.20.0
    releaseName: external-dns
    namespace: external-dns
    includeCRDs: true
    valuesFile: ./values.yaml

resources:
  - dns/github-pages.yaml

generators:
  - ksops.yaml
