apiVersion: v1
kind: Secret
metadata:
    name: traefik-basic-auth
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4ADOkzmizw==,iv:b68ibWP8hllOpJVKVr5cNqtPxQKErB0hKXGdpBrY4mg=,tag:Pkws+2v1+R6Vsr2vnVs8vg==,type:str]
    password: ENC[AES256_GCM,data:4jHpz2uCzqs3ZXtlrT1EPoxOCXk=,iv:fxCGViel/hAVxddz/POyPDtRcnJUAFTbx0nuDj48hWE=,tag:wXsxJ6TMu4yWJguFiHvVGw==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY2JJWFdhQlZSZDNLRkh3
            VHFDTWN6WUVDMGRZOW4vd2o3R1pCWFZwcjFFCnhmY3VhUTVUUS9lcnFldHZHWExZ
            UExtK2V3VXp0K2l3MVRpeVkxL3pVdGsKLS0tIDEvc0tGbnc5YnIvUkxvWlJuVnVT
            alllOEg1ckE5K0JqcExVTVZtdU0wUmMKRJSebd2Vx3awnDwVGASrTCkm1k5ytpE+
            ZoIezh0+S7NPK+3gjq6QmxCdt2LLjGLx5ItD5x8STuoENOM06Zdy1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T15:14:06Z"
    mac: ENC[AES256_GCM,data:wURA2MkzxSqJ+79ynKlWALRhxANV/ZyGbrf6Qgd7l5SX4GdlU4+4y0e8ZTW7jhIspg2EoMAa92VH6355kx1AJRa9Kid2W0XnB9kv/yC48d3QjpKCuSghQvAU20YwQV7qtRUE66qqJZjeM9NWRVpF8/cK0QAVy7bSKd5xIqMUbN8=,iv:y1/frMDnPmX6J5S+oGkiQbcEsUi6FLssFoRZfkWNgAE=,tag:xCRs/K13zpdSyQWFXqsrzg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
