apiVersion: v1
kind: Secret
metadata:
    name: argo-workflows-basic-auth
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CcoLrybZgQ==,iv:XdnUkMZ82dwPY1zoxWvJD5gQ0rmIlDPmem+n1WFbW/I=,tag:5W1ccqf69HnBk35T7eYYFA==,type:str]
    password: ENC[AES256_GCM,data:rYAoH+DWUCdkZjJUbkPvfupIWZk=,iv:HLyOBBNG1b7BjmrJP/qisK0phZSLlJnj1heSfYyzbm4=,tag:iZGrE+pfuEcU2eNrdeWfGw==,type:str]
sops:
    age:
        - recipient: age16uagmx40mgwq3cgpqc5h78fgxypd5yngqltnqc2fk0j5q9alry6qp3dt25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWFdZMFIzZUpiOVhlVzkv
            OUV1NnRUNGRaNGsvZTVSTUZzTmJjM3NNeHdVCkY3NDBFYkF4bUtxa01sbEoxL2hn
            akNOVGdRZk9aVTU3MkVaWXRRa2NhZzQKLS0tIEhibVRYNUZQRnhxWC9kT0JSam80
            TlNpQXk0alVUbDJqS3U5U0lKWmxoWmMKvK25vThrjchCAfIdvRi4uQaGKh+uawWf
            MqABVRFeWeORXPkg90KBa1z/rhVru7ZCWtCdcwnnWHwaOPYUY2wPXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T15:09:38Z"
    mac: ENC[AES256_GCM,data:7PR1zJ3TI/H+qQa6zWQmNyVOO9QP/fif0OVaHAIsDypLxpbeKw6gxOd+/SHAL8DYuyp5qQqavuVVOL+MMkxOh5NSwSSzKkAPtcPlodfgyZV9kc8vASHF2pId1E6BCqhsmoU0OKaAp2UvAedZkRTPhPqbdiBjb3wh7ap3RKYlXWY=,iv:m68KlczzbHHkTO7P3tvHKx2cvG3PDUxWyUb6vpeTdt4=,tag:GDofjUFV3NiP0MYVOWQNUQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
